//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Serial
    {
        public long ID { get; set; }
        public string RawBarcode { get; set; }
        public string Item_Code { get; set; }
        public string Serial_Number { get; set; }
        public string Description { get; set; }
        public string Behaviour { get; set; }
        public string ApprovedBy { get; set; }
        public string Reason { get; set; }
        public string ScannedBy { get; set; }
        public string DateScanned { get; set; }
        public Nullable<long> FileInfoID { get; set; }
        public Nullable<System.DateTime> DateAudited { get; set; }
        public Nullable<int> ImportStatus { get; set; }
    }
}
