//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.ProductCatalogs = new HashSet<ProductCatalog>();
        }
    
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public System.Guid guid { get; set; }
        public byte[] checksum { get; set; }
        public string name { get; set; }
        public int nestedLevel { get; set; }
        public int relativePosition { get; set; }
        public string tags { get; set; }
        public string description { get; set; }
        public int behaviour { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string PastelCode { get; set; }
    
        public virtual ICollection<ProductCatalog> ProductCatalogs { get; set; }
    }
}
