//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public System.Guid Rowguid { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public byte[] Checksum { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingAddress3 { get; set; }
        public string ShippingAddress4 { get; set; }
        public string ShippingAddressCode { get; set; }
        public string ShippingAddressCountry { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingAddress4 { get; set; }
        public string BillingAddressCode { get; set; }
        public string BillingAddressCountry { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string SwitchboardNumber { get; set; }
        public Nullable<System.Guid> SalesRepGuid { get; set; }
    }
}
