//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequest
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public System.Guid guid { get; set; }
        public long CustomerId { get; set; }
        public string Description { get; set; }
        public string OrderNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public string RequestStatus { get; set; }
        public string ItemSerialNumber { get; set; }
    }
}
