//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Todoes = new HashSet<Todo>();
        }
    
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public System.Guid guid { get; set; }
        public byte[] checksum { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string password { get; set; }
        public long AccountId { get; set; }
        public Nullable<long> TemplateId { get; set; }
        public Nullable<System.Guid> SalesRepGuid { get; set; }
        public Nullable<System.DateTime> PasswordExpiryDate { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public Nullable<long> YearsInBusiness { get; set; }
        public string DateEstablished { get; set; }
        public string ShipMainPhoneNumber { get; set; }
        public Nullable<long> NumberOfEmployees { get; set; }
        public string ShipWebsite { get; set; }
        public string ShipEmail { get; set; }
        public string ShipTypeOfBusiness { get; set; }
        public string CustDelivCode { get; set; }
        public Nullable<bool> AdminRights { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> Archive { get; set; }
        public string APIToken { get; set; }
    
        public virtual ICollection<Todo> Todoes { get; set; }
    }
}
