//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentComment
    {
        public System.Guid Rowguid { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public byte[] Checksum { get; set; }
        public string Comment { get; set; }
        public long DocumentId { get; set; }
        public Nullable<System.Guid> SalesRepGuid { get; set; }
        public Nullable<System.Guid> CustomerGuid { get; set; }
        public int AddedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> SystemGen { get; set; }
        public string Name { get; set; }
    }
}
