//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public System.Guid guid { get; set; }
        public byte[] checksum { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public double quantity { get; set; }
        public double unitPriceExcl { get; set; }
        public double unitPriceIncl { get; set; }
        public double unitTaxAmount { get; set; }
        public double totalPriceExcl { get; set; }
        public double totalPriceIncl { get; set; }
        public double totalTax { get; set; }
        public string additionalInformation { get; set; }
        public long DocumentId { get; set; }
        public System.Guid LineTypeGuid { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<double> Markup { get; set; }
        public string BrandType { get; set; }
        public string BrandColour { get; set; }
        public string Size { get; set; }
        public string Colour { get; set; }
        public string ExpandedCode { get; set; }
        public bool LineAccepted { get; set; }
        public double QtyAllocate { get; set; }
        public double QtyBackOrder { get; set; }
        public int SerializedStatus { get; set; }
        public double GPPO { get; set; }
        public double RCT { get; set; }
        public double POD { get; set; }
        public double INV { get; set; }
        public double QTYAVL { get; set; }
        public string StockStoreCode { get; set; }
        public double DealerPrice { get; set; }
        public string PastelBackorder { get; set; }
        public Nullable<double> InitialPrice { get; set; }
        public Nullable<bool> AsDiscount { get; set; }
        public Nullable<double> DiscountPerc { get; set; }
    }
}
