//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OE_DocumentConfiguration
    {
        public long id { get; set; }
        public long DocumentId { get; set; }
        public int OrderType { get; set; }
        public int ProcessType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
        public Nullable<System.Guid> SalesRepExec { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string CustomerPONumber { get; set; }
        public string GPOrderRef { get; set; }
        public string SalesRepCode { get; set; }
        public string MonthlyTerms { get; set; }
    }
}
