//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastelPO
    {
        public System.Guid guid { get; set; }
        public string Supplier { get; set; }
        public string PO { get; set; }
        public string ItemCode { get; set; }
        public string StockETA { get; set; }
        public Nullable<int> QtyComming { get; set; }
        public Nullable<bool> Updated { get; set; }
    }
}
