//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pastel_OpenItem
    {
        public long Id { get; set; }
        public string DC { get; set; }
        public string Original { get; set; }
        public string cscode { get; set; }
        public string matchref { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public string entrytype { get; set; }
        public string @ref { get; set; }
        public Nullable<double> amount { get; set; }
        public string description { get; set; }
        public string PPeriod { get; set; }
    }
}
