//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pastel_PaymentsForInvoices
    {
        public long id { get; set; }
        public string GDC { get; set; }
        public string AccNumber { get; set; }
        public string PPeriod { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
        public string EType { get; set; }
        public string Refrence { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Description { get; set; }
        public string Autonumber { get; set; }
    }
}
