//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastelAccountBalance
    {
        public long id { get; set; }
        public string CustomerCode { get; set; }
        public string BalanceThis01 { get; set; }
        public string BalanceThis02 { get; set; }
        public string BalanceThis03 { get; set; }
        public string BalanceThis04 { get; set; }
        public string BalanceThis05 { get; set; }
        public string BalanceThis06 { get; set; }
        public string BalanceThis07 { get; set; }
        public string BalanceThis08 { get; set; }
        public string BalanceThis09 { get; set; }
        public string BalanceThis10 { get; set; }
        public string BalanceThis11 { get; set; }
        public string BalanceThis12 { get; set; }
        public string BalanceThis13 { get; set; }
        public string BalanceLast01 { get; set; }
        public string BalanceLast02 { get; set; }
        public string BalanceLast03 { get; set; }
        public string BalanceLast04 { get; set; }
        public string BalanceLast05 { get; set; }
        public string BalanceLast06 { get; set; }
        public string BalanceLast07 { get; set; }
        public string BalanceLast08 { get; set; }
        public string BalanceLast09 { get; set; }
        public string BalanceLast10 { get; set; }
        public string BalanceLast11 { get; set; }
        public string BalanceLast12 { get; set; }
        public string BalanceLast13 { get; set; }
        public string SalesThis01 { get; set; }
        public string SalesThis02 { get; set; }
        public string SalesThis03 { get; set; }
        public string SalesThis04 { get; set; }
        public string SalesThis05 { get; set; }
        public string SalesThis06 { get; set; }
        public string SalesThis07 { get; set; }
        public string SalesThis08 { get; set; }
        public string SalesThis09 { get; set; }
        public string SalesThis10 { get; set; }
        public string SalesThis11 { get; set; }
        public string SalesThis12 { get; set; }
        public string SalesThis13 { get; set; }
        public string SalesLast01 { get; set; }
        public string SalesLast02 { get; set; }
        public string SalesLast03 { get; set; }
        public string SalesLast04 { get; set; }
        public string SalesLast05 { get; set; }
        public string SalesLast06 { get; set; }
        public string SalesLast07 { get; set; }
        public string SalesLast08 { get; set; }
        public string SalesLast09 { get; set; }
        public string SalesLast10 { get; set; }
        public string SalesLast11 { get; set; }
        public string SalesLast12 { get; set; }
        public string SalesLast13 { get; set; }
        public string Ageing01 { get; set; }
        public string Ageing02 { get; set; }
        public string Ageing03 { get; set; }
        public string Ageing04 { get; set; }
        public string Ageing05 { get; set; }
        public string PerStartThis01 { get; set; }
        public string PerStartThis02 { get; set; }
        public string PerStartThis03 { get; set; }
        public string PerStartThis04 { get; set; }
        public string PerStartThis05 { get; set; }
        public string PerStartThis06 { get; set; }
        public string PerStartThis07 { get; set; }
        public string PerStartThis08 { get; set; }
        public string PerStartThis09 { get; set; }
        public string PerStartThis10 { get; set; }
        public string PerStartThis11 { get; set; }
        public string PerStartThis12 { get; set; }
        public string PerStartThis13 { get; set; }
        public string PerEndThis01 { get; set; }
        public string PerEndThis02 { get; set; }
        public string PerEndThis03 { get; set; }
        public string PerEndThis04 { get; set; }
        public string PerEndThis05 { get; set; }
        public string PerEndThis06 { get; set; }
        public string PerEndThis07 { get; set; }
        public string PerEndThis08 { get; set; }
        public string PerEndThis09 { get; set; }
        public string PerEndThis10 { get; set; }
        public string PerEndThis11 { get; set; }
        public string PerEndThis12 { get; set; }
        public string PerEndThis13 { get; set; }
        public string PerStartLast01 { get; set; }
        public string PerStartLast02 { get; set; }
        public string PerStartLast03 { get; set; }
        public string PerStartLast04 { get; set; }
        public string PerStartLast05 { get; set; }
        public string PerStartLast06 { get; set; }
        public string PerStartLast07 { get; set; }
        public string PerStartLast08 { get; set; }
        public string PerStartLast09 { get; set; }
        public string PerStartLast10 { get; set; }
        public string PerStartLast11 { get; set; }
        public string PerStartLast12 { get; set; }
        public string PerStartLast13 { get; set; }
        public string PerEndLast01 { get; set; }
        public string PerEndLast02 { get; set; }
        public string PerEndLast03 { get; set; }
        public string PerEndLast04 { get; set; }
        public string PerEndLast05 { get; set; }
        public string PerEndLast06 { get; set; }
        public string PerEndLast07 { get; set; }
        public string PerEndLast08 { get; set; }
        public string PerEndLast09 { get; set; }
        public string PerEndLast10 { get; set; }
        public string PerEndLast11 { get; set; }
        public string PerEndLast12 { get; set; }
        public string PerEndLast13 { get; set; }
        public string CreditLimit { get; set; }
    }
}
