//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEORouting
    {
        public System.Guid routid { get; set; }
        public string RouteParam1 { get; set; }
        public string RouteParam2 { get; set; }
        public int RouteType { get; set; }
        public Nullable<System.Guid> RouteDataGuid { get; set; }
        public string RouteDataString { get; set; }
        public string RouteDataOption { get; set; }
    }
}
