//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public System.Guid guid { get; set; }
        public byte[] checksum { get; set; }
        public int type { get; set; }
        public string group { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string stringValue { get; set; }
        public Nullable<System.DateTime> dateValue { get; set; }
        public Nullable<long> integralValue { get; set; }
        public Nullable<double> floatValue { get; set; }
        public string optionValue { get; set; }
        public string availableOptions { get; set; }
        public Nullable<bool> boolValue { get; set; }
    }
}
