//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierBrandings = new HashSet<SupplierBranding>();
            this.SupplierBrandPricings = new HashSet<SupplierBrandPricing>();
        }
    
        public long Id { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public byte[] Checksum { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Url { get; set; }
        public string LogoUrl { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public int Status { get; set; }
        public string CompanyRegistration { get; set; }
        public string VATRegistration { get; set; }
        public string PhysicalAddress { get; set; }
        public string PhysicalCode { get; set; }
        public string PostalAddress { get; set; }
        public string PostalCode { get; set; }
        public string PCFirstname { get; set; }
        public string PCLastname { get; set; }
        public int PositionInCompany { get; set; }
        public string PCPhone { get; set; }
        public string PCSkype { get; set; }
        public string PCEmail { get; set; }
        public string PCCell { get; set; }
        public string BillingJobTitle { get; set; }
        public string BillingFirstname { get; set; }
        public string BillingLastname { get; set; }
        public string BillingPhone { get; set; }
        public string BillingFax { get; set; }
        public string BillingEmail { get; set; }
        public string BillingCell { get; set; }
        public string OrderFirstname { get; set; }
        public string OrderLastname { get; set; }
        public string OrderPhone { get; set; }
        public string OrderFax { get; set; }
        public string OrderEmail { get; set; }
        public string Terms { get; set; }
        public string BankName { get; set; }
        public string BranchCode { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
    
        public virtual ICollection<SupplierBranding> SupplierBrandings { get; set; }
        public virtual ICollection<SupplierBrandPricing> SupplierBrandPricings { get; set; }
    }
}
