//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriboschAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenSaleRep
    {
        public long TokenId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AuthToken { get; set; }
        public Nullable<System.DateTime> IssuedOn { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
    }
}
