//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProductLineBrand
    {
        public long id { get; set; }
        public System.DateTime modified { get; set; }
        public string HomeTheaterComponents { get; set; }
        public string DistributedAudio { get; set; }
        public string Lightning { get; set; }
        public string HVAC { get; set; }
        public string Secutiry { get; set; }
        public string Speakers { get; set; }
        public string Control { get; set; }
        public string TvDisplays { get; set; }
        public Nullable<long> CustomerID { get; set; }
    }
}
