//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBusinessInfo
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public System.Guid guid { get; set; }
        public byte[] checksum { get; set; }
        public string InfoEmployees { get; set; }
        public string InfoJobsAvgPerYear { get; set; }
        public string InfoSalesPeople { get; set; }
        public string InfoPercJobsNewConstruction { get; set; }
        public string InfoInstallers { get; set; }
        public string InfoPercJobsRetroFit { get; set; }
        public string InfoBuilderRelationship { get; set; }
        public string InfoPercJobsCommercial { get; set; }
        public string InfoEquipmentBilling { get; set; }
        public string InfoAvgLabourBillingPerJob { get; set; }
        public string CompanyRevenueLastYear { get; set; }
        public string InfoProjectionRevenueThisYear { get; set; }
        public string SystemProgramming { get; set; }
        public string InfoNetworkingBackground { get; set; }
        public string InfoSystemProgrammingBackground { get; set; }
        public string InfoInstallersReceiveSpecialTrainingCert { get; set; }
        public string InfoProdStaffTraining { get; set; }
        public string InfoHmProdLineFit { get; set; }
        public Nullable<long> CustomerID { get; set; }
    }
}
