//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentEndUserDelivery
    {
        public System.Guid Rowguid { get; set; }
        public System.DateTime Created { get; set; }
        public byte[] Checksum { get; set; }
        public string EndUserName { get; set; }
        public string EndUserCompanyName { get; set; }
        public string EndUserPhone { get; set; }
        public string EndUserEmail { get; set; }
        public string EndUserCompanyAddress1 { get; set; }
        public string EndUserCompanyAddress2 { get; set; }
        public string EndUserCompanyAddressCity { get; set; }
        public string EndUserCompanyAddressProvince { get; set; }
        public string EndUserCompanyAddressCode { get; set; }
        public string EndUserCompanyAddressCountry { get; set; }
        public string DocumentGuid { get; set; }
    }
}
