//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileInfo
    {
        public long FInfoID { get; set; }
        public Nullable<int> FileTypeID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateLogged { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public Nullable<int> LineCount { get; set; }
        public string Description { get; set; }
        public Nullable<int> Inserted { get; set; }
        public Nullable<int> Back { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> Hidden { get; set; }
        public Nullable<int> Exist { get; set; }
    }
}
