//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceNumber
    {
        public System.Guid Rowguid { get; set; }
        public System.DateTime created { get; set; }
        public System.Guid DocumentGuid { get; set; }
        public string number { get; set; }
        public Nullable<bool> Notified { get; set; }
        public Nullable<bool> Released { get; set; }
    }
}
