//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int LineId { get; set; }
        public string LineDescription { get; set; }
        public string LineQty { get; set; }
        public Nullable<double> LinePriceExcl { get; set; }
        public Nullable<double> LinePriceIncl { get; set; }
        public Nullable<double> LineVat { get; set; }
        public string LineSize { get; set; }
        public int DocumentId { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
