//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pastel_PaymentCheck
    {
        public long ID { get; set; }
        public string CustomerCode { get; set; }
        public string lastCRDate { get; set; }
        public string LastCRAmount { get; set; }
        public Nullable<System.DateTime> DateImported { get; set; }
    }
}
