//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListManufacture
    {
        public System.Guid guid { get; set; }
        public System.Guid PriceListGuid { get; set; }
        public long ManufactureId { get; set; }
    }
}
