//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSegmentationGroupPrice
    {
        public long Id { get; set; }
        public float Price { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public System.Guid ProductSegmentationGuid { get; set; }
        public System.Guid GroupGuid { get; set; }
        public System.Guid ProductGuid { get; set; }
    }
}
