//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductCatalogs = new HashSet<ProductCatalog>();
            this.ProductSegmentations = new HashSet<ProductSegmentation>();
            this.ProductBrandings = new HashSet<ProductBranding>();
        }
    
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public System.Guid guid { get; set; }
        public byte[] checksum { get; set; }
        public int type { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> volume { get; set; }
        public int availability { get; set; }
        public System.DateTime availabilityETA { get; set; }
        public double availableQuantity { get; set; }
        public int behavior { get; set; }
        public int promotion { get; set; }
        public string tags { get; set; }
        public string description { get; set; }
        public string segmentation { get; set; }
        public Nullable<long> ManufacturerId { get; set; }
        public Nullable<long> TemplateId { get; set; }
        public Nullable<double> Markup { get; set; }
        public bool NonVat { get; set; }
        public bool autoupdate { get; set; }
        public Nullable<long> FileID { get; set; }
        public bool autoUpdated { get; set; }
        public Nullable<double> DefaultCommissionPerc { get; set; }
        public string ProductCommonFactor { get; set; }
        public string PackType { get; set; }
        public double RetailPrice { get; set; }
        public bool HaveSerial { get; set; }
        public string Pasteluserdeftext01 { get; set; }
        public string PastelStockETA { get; set; }
        public string PastelQtyOnHand { get; set; }
        public string PastelBINLocation { get; set; }
        public string PastelUOM { get; set; }
        public string PastelDiscountType { get; set; }
        public Nullable<int> PastelBlocked { get; set; }
        public string RelatedProducts { get; set; }
        public Nullable<bool> ModifiedByUser { get; set; }
        public Nullable<int> SerialQty { get; set; }
    
        public virtual ICollection<ProductCatalog> ProductCatalogs { get; set; }
        public virtual ICollection<ProductSegmentation> ProductSegmentations { get; set; }
        public virtual ICollection<ProductBranding> ProductBrandings { get; set; }
    }
}
