//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafeShop
    {
        public long id { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid DocumentGuid { get; set; }
        public string SafePayRefNr { get; set; }
        public string BankRefNr { get; set; }
        public string Ref { get; set; }
        public int PaymentStatus { get; set; }
        public string XmlResponse { get; set; }
    }
}
