//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRep
    {
        public SalesRep()
        {
            this.SalesRepCommunications = new HashSet<SalesRepCommunication>();
            this.Todoes = new HashSet<Todo>();
        }
    
        public System.Guid rowguid { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public byte[] checksum { get; set; }
        public Nullable<System.Guid> SalesRepParentGuid { get; set; }
        public string SalesRepCode { get; set; }
        public string SalesRepExternalId { get; set; }
        public string name { get; set; }
        public System.Guid SalesRepTypeGuid { get; set; }
        public string surname { get; set; }
        public string mobile { get; set; }
        public string Landline { get; set; }
        public int Status { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public double Target { get; set; }
        public string Template { get; set; }
        public string GeneralFax { get; set; }
        public string DirectFax { get; set; }
        public bool HideDashboard { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public string StoreCode { get; set; }
        public Nullable<bool> FromPastel { get; set; }
    
        public virtual ICollection<SalesRepCommunication> SalesRepCommunications { get; set; }
        public virtual ICollection<Todo> Todoes { get; set; }
    }
}
