//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRepCommunication
    {
        public SalesRepCommunication()
        {
            this.CustomerCommunications = new HashSet<CustomerCommunication>();
        }
    
        public System.Guid guid { get; set; }
        public System.DateTime created { get; set; }
        public System.Guid salesRepGuid { get; set; }
        public string message { get; set; }
        public Nullable<System.Guid> documentGuid { get; set; }
    
        public virtual ICollection<CustomerCommunication> CustomerCommunications { get; set; }
        public virtual SalesRep SalesRep { get; set; }
    }
}
