//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemation.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public System.Guid rowguid { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public System.Guid SalesRepGuid { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public int priority { get; set; }
        public string action { get; set; }
        public System.DateTime actionDate { get; set; }
        public int status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesRep SalesRep { get; set; }
    }
}
