//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriboschAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public int LineID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> TotalExcl { get; set; }
        public Nullable<double> TotalIncl { get; set; }
        public int docID { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
